### PR TITLE
Project structure refactoring & packing

### PR DESCRIPTION
**Pull request by Bodong-Yang**
## Introduction
This PR refactors the project structures aligned to the convention, re-arrange previously separated top-layer modules `app`, `aws_iot_log_server` and `ota_proxy` under one single `otaclient` top-layer package. It also configures the `pyproject.toml` to make the project ready for distribution.

Build tar.gz archive and wheel for distribution are also possible.

### Installation
NOTE: upgrade setuptools, setuptools-scm and pip before installation
1. git clone the  specific branch/tag to a temporary folder
```bash
git clone https://github.com/tier4/ota-client /tmp
```
2. prepare virtual env and activate it
```bash
python3 -m venv /opt/ota/.venv
source /opt/ota/.venv/bin/activate
```
4. install dependencies for otaclient with pip
```bash
# NOTE: we will not use the otaclient installed here, 
# check the following instructions
pip install /tmp/ota-client
```
5. install the otaclient package to /opt/ota
```bash
# NOTE: --no-deps MUST be set, otherwise all dependencies 
#              will also be installed under /opt/ota
pip install -t /opt/ota --no-deps /tmp/ota-client
# cleanup
rm -rf /opt/ota/otaclient*dist-info
rm -rf /tmp/ota-client
```
#### method 1
```bash
# we have to append the /opt/ota to the PYTHONPATH, to tell the 
# python interpreter to search otaclient package under /opt/ota, instead of 
# using the one installed under <virtualenv>/lib/python3.8/site-packages

# with venv activated: 
PYTHONPATH=/opt/ota python3 -m otaclient
# or
PYTHONPATH=/opt/ota python3 -m otaclient.app
````

#### method 2
```bash
# change work dir to /opt/ota
cd /opt/ota

# with venv activated:
# NOTE:python will insert current working dir at index 0 in `sys.path`
# under /opt/ota folder, so that python will first use otaclient under /opt/ota
python3 -m otaclient 
# or
python3 -m otaclient.app
```

### launch aws_iot_log_server
```
cd /opt/ota

# with venv enabled, under the /opt/ota folder
python3 -m aws_iot_log_server \
    --host 0.0.0.0 \
    --port {{ ota_client_log_server_port }} \
    --aws_credential_provider_endpoint ${AWS_CREDENTIAL_PROVIDER_ENDPOINT} \
    --aws_role_alias ${AWS_ROLE_ALIAS} \
    --aws_cloudwatch_log_group ${AWS_CLOUDWATCH_LOG_GROUP} \
    --greengrass_config ${AWS_GREENGRASS_CONFIG}
```

## NOTE
1. bootstrap like install otaclient.service unit file cannot be done by pip.
2. pip currently doesn't have --only-deps options, so we have to first install otaclient normally to install all dependencies under viritualenv's default lib path, and then install otaclient with --no-deps option to custom folder(/opt/ota).
3. -t option MUST be used together with --no-deps, otherwise otaclient along with all dependencies will be installed to -t <folder>.

## Changes
1. refactoring project structure
2. use relative module paths internally for `app` and `aws_iot_log_server`
3. finally solve the import path issue, all the workarounds are removed now
4. configure project metadata in `pyproject.toml`, supporting packaging and distributing otaclient project
5. (FIX) ota_client: add type guard when parsing cookie json, expecting dict
6. (FIX/REFINEMENT) fix test files for aws_iot_log_server, remove old test dependency
9. bump test dependencies, remove unused dep
10. use `version` generated by `setuptools-scm`

## TODO
Helper packages under `tools/` are not yet updated to work under the new otaclient module structure.

### CODE REVIEW

**Comment by Bodong-Yang** [comment]
@obi-t4 Does `aws-iot-log-server` also need to be run independently? If so I have to adjust the repo again.

**Comment by obi-t4** [comment]
@Bodong-Yang 
aws-iot-log-server is started from:
https://github.com/tier4/autoware_ecu_system_setup/blob/main/roles/ota_client_logger/templates/aws-iot-log-server.sh.j2
So it runs independently.

**Comment by Bodong-Yang** [comment]
> @Bodong-Yang aws-iot-log-server is started from: https://github.com/tier4/autoware_ecu_system_setup/blob/main/roles/ota_client_logger/templates/aws-iot-log-server.sh.j2 So it runs independently.

@obi-t4 With latest commit, `aws-iot-log-server` can be launched directly, please check PR introduction for details.

**Review by obi-t4 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
