### PR TITLE
Fix backward compatibility broken on grub controller

### PR DESCRIPTION
**Pull request by Bodong-Yang**
## Introduction
This PR fix [T4PB-19317](https://tier4.atlassian.net/browse/T4PB-19317), the issue that breaks the backward compatibility when downgrading from new otaclient from `otaclient_refactoring3_rc` branch to current main branch.
The cause of the issue is that `grub_control` module in `otaclient_refactoring3_rc` use `PARTUUID` to specify rootfs instead of  `UUID`, which breaks the `grub_control` module in current main branch.

This PR uses `UUID` to indicates rootfs again to maintain backward compatibility.

## Changes
1. still use UUID to indicate rootfs when generating new `grub.cfg`,
2. helper method `mkfs.ext4` now will inherit the old `UUID` when formatting.

## Test
The following steps are applied to test this PR:
1. `sda2`: update using `otaclient_refactoring3_rc` to slot `sda3`
2. `sda3`: update using current main branch to slot `sda2`

### CODE REVIEW

**Comment by obi-t4** [comment]
- [ ] prev image -> this PR
- [ ] this PR -> prev image
- [ ] prev image -> this PR
- [ ] this PR -> this PR
- [ ] initial -> this PR
- [ ] this PR interrupted and rebooted

**Comment by obi-t4** [comment]
@Bodong-Yang 
the status response doesn't contain total_regular_file_size. Can you confirm?

**Comment by obi-t4** [comment]
> the status response doesn't contain total_regular_file_size. Can you confirm?

This problem may or may not occur.

**Comment by Bodong-Yang** [comment]
> > the status response doesn't contain total_regular_file_size. Can you confirm?
> 
> This problem may or may not occur.

This PR doesn't touch codes that related to this issue, another PR is needed for this.

**Comment by obi-t4** [comment]
@Bodong-Yang Sorry, metadata.jwt didn't contain total_regula_size filed :pray:

**Review by obi-t4 — APPROVED** [review]
LGTM :+1: 
I think there is no left issue!

**Pull request merged**
