### PR TITLE
fix: python path to use venv

### PR DESCRIPTION
**Pull request by obi-t4**
Use venv's python3

### CODE REVIEW

**Comment by obi-t4** [comment]
I'll convert to this PR to draft.

**Comment by obi-t4** [comment]
changed to ready-for-review.

**Comment by Bodong-Yang** [comment]
@obi-t4 where will the otaclient installed to? In this service unit file it expects `/opt/ota/otaclient`, but I notice that in firmware version `20221013091746-22.04-1st-sub`, otaclient is located at `/opt/ota/client/otaclient`. 
But it seems that the systemd service unit file will be updated when installed by ansible though.

**Comment by obi-t4** [comment]
@Bodong-Yang 

> in firmware version 20221013091746-22.04-1st-sub, otaclient is located at /opt/ota/client/otaclient.

That is true. It is the user's responsibility to deiced where to install it. So 20221013091746-22.04-1st-sub is OK.

But the code **before** this change, /usr/bin/python3 is referenced even /opt/ota/.venv is used. It is completely wrong.

**Review by Bodong-Yang — APPROVED** [review]

**Pull request merged**
