### PR TITLE
docs: update DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by airkei**
### Why
`docs/` directory is no more used, but the instructions in `DEVELOPMENT.md` still refer docs directory.

### What
Update `DEVELOPMENT.md` to describe the current procedure.

### CODE REVIEW

**Comment by Bodong-Yang** [comment]
@airkei Thank you for the PR! 👍 
However their is pitfall that, by just installing otaclient you will (probably) not be able to get it work, as we need to pre-configure the system before it can work.

Currently we are using ansible to setup the system and install otaclient. But that ansible playbook, as you know, is not public, so we cannot just copy-paste it to this repository.

Actually I think currently we should just completely remove this doc.

**Comment by airkei** [comment]
@Bodong-Yang Thank you for feedback. As you say, we should not describe the instructions which depends on non-public   setup. On the other hand, I think it's better to describe the instructions as much as possible in markdown.
How about to remove the ECU installation part and keep tests parts like the latest commit?

**Comment by Bodong-Yang** [comment]
> How about to remove the ECU installation part and keep tests parts like the latest commit?

I think this is OK for now. In the future, we can write a detailed installation guide based on the ansible playbook, or even provide a stripped down version of the ansible role that only setup otaclient.

**Review by Bodong-Yang — APPROVED** [review]
Let's remove the installation part for now. 👍 
In the future we can either provide a full and detailed guide of setting up device system and otaclient, or even provide a stripped down version of otaclient installation role.

**Pull request merged**
