### PR TITLE
[Bugfix] otaproxy: fix AsyncStopIteration errors spamming

### PR DESCRIPTION
**Pull request by Bodong-Yang**
## Introduction
This PR fixes otaproxy spams `cache write failed: AsyncStopIteration` logs caused by `_cache_streamer` doesn't skip empty chunk.
When HTTP chunk encoding is enabled, a empty chunk will be sent to indicate the end of chunk streaming, previously the otaproxy will not skip this empty chunk and also send it to client and the caching generator. And when multiple otaproxy chained together, multiple empty chunks will be sent to the client(one more empty chunk for passing one more otaproxy), causing the problem.

## Changes
1. _cache_streamer: skip the empty chunk

### CODE REVIEW

**Comment by obi-t4** [comment]
@Bodong-Yang 
Can we re-produce this `AsyncStopIteration errors` on the current main branch?

**Comment by Bodong-Yang** [comment]
> @Bodong-Yang Can we re-produce this `AsyncStopIteration errors` on the current main branch?

I guess if the `upper_ota_proxy` enables the HTTP chunk streaming, then this behavior can be reproduced?

**Comment by obi-t4** [comment]
@Bodong-Yang 

> I guess if the upper_ota_proxy enables the HTTP chunk streaming, then this behavior can be reproduced?

In other words, how did you debug this feature, how did you confirmed that the issue is resolved?
I'd like to make sure it on this review.

**Comment by Bodong-Yang** [comment]
> @Bodong-Yang
> 
> > I guess if the upper_ota_proxy enables the HTTP chunk streaming, then this behavior can be reproduced?
> 
> In other words, how did you debug this feature, how did you confirmed that the issue is resolved? I'd like to make sure it on this review.

Ah I basically debug by reading code along with the syslog you provided to me, and I come to the solution. I will do test to confirm it, please wait for some time.

**Comment by Bodong-Yang** [comment]
@obi-t4 I can reproduce the issue by chaining 3 otaproxy together, and also confirmed that this PR does fix the problem

**Review by obi-t4 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
