### PR TITLE
[Chore] tag v3.5.0 (20230530)

### PR DESCRIPTION
**Pull request by obi-t4**
## Description

chore commit for taggin v3.5.0.

## Commits since [v3.4.1](https://github.com/tier4/ota-client/releases/tag/v3.4.1)

[`tag/v3.4.1...chore/v3.5.0`](https://github.com/tier4/ota-client/compare/v3.4.1...chore/v3.5.0)

### New feature

1. #212 

### Bug fix

1. #211 
2. #213 
3. #215 
4. #217 
5. #222 

### Refinement

1. #214 
2. #218 
3. #219 
4. #222 
5. #221 
6. #224 
7. #212 

### Chore

1. #220 
2. #223 

### Deps

1. #226 

### User experience changes

1. #212 :
    1. now otaclient supports update only a portion of ECUs in the cluster(may or may not include self ECU itself),
    2. now otaclient supports retry on OTA failed ECU at anytime, regardless if there is any other ECU in update or not,
    3. use ensure_otaproxy_start from https://github.com/tier4/ota-client/pull/219, now otaclient will wait for upper otaproxy(if any) online before starting any downloading,
    4. otaclient still waits for its all its childECUs not in UPDATING ota_status before it can reboot itself(to finalize its OTA update, if applicable), but if the only leftover in UPDATING ECU become unreachable, it will not wait for it and reboot,
    5. otaclient status API will return the cached ECU status reports for each ECUs. If disconnected ECU labelled as unreachable(disconnected longer than UNREACHABLE_ECU_TIMEOUT), this ECU's cached status report will be removed from mainECU's status API response.

2. #219 
    1. If `upper_ota_proxy` is configured and `enable_local_ota_proxy` is True in `proxy_info.yaml`, otaclient will wait for `upper_ota_proxy` becoming online before it starts any downloading.

3. #215 
    1. now OTA metadata & meta files downloading are also covered by same retry strategy as OTA files downloading.

### Internal changes

1. #212 
    1. now otaclient will continuously polls status from subECUs(with ACTIVE_POLLING_INTERVAL or IDLE_POLLING_INTERVAL),
    2. now otaclient supports handling/dispatching OTA request at anytime, regardless if there is any other ECU in update or not,
    3. now otaclient supports discovering in UPDATING ECU and launch otaproxy on-demand(when any ECU requires network) at anytime,
    4. now otaclient will cleanup cache_dir in current ACTIVE SLOT when all child ECUs/self ECU in the cluster is in SUCCESS ota_status, (NOTE that standby slot's ota_cache dir will not be cleaned),
    5. otaclient will cache status report from child ECUs, instead of querying each subECUs' status API when mainECU's status API is called, and return the latest one as status API querying response, except for status report for (labelled as)unreachable/disconnected ECU(entry excluded from the response),
    6. ECU that keeps disconnected longer than UNREACHABLE_ECU_TIMEOUT will be treated as unreachable, this ECU will be excluded from overall_ecu_status_report generation, hence excluded from the factors of blocking mainECU from rebooting, also this ECU's status report will be removed when generating status API response,
    7. OTAClientServiceStub now only controls OTAClient reboot behavior, permit/prevent it reboots the ECU in multiple ECU scenarios.

2. #222 
    1. for valid metadata.jwt that missing optional fields, proper default value will be set after parsing:
        a. `total_regular_size -> 0`,
        b. `compressed_rootfs_directory -> ""`,
    2. for invalid metadata.jwt(either invalid json, or missing must_set fields), MetadataJWTPayloadInvalid OTA recoverable error will be reported.
    3. OTA recoverable error BaseOTAMetaVerificationFailed now is renamed to MetadataJWTVerficationFailed.

3. #211 
    1. files being copied from active slot to standby slot will be validated by hashing during the copying.

### Noticeable unchanged behaviors

1. #212 
    1. use updated otaclient_call from #224 , and again ensure the behavior of:
    if subECU doesn't respond to dispatched OTA request, otaclient will create a response with OTA RECOVERABLE failure for it.
    2. otaclient status API will not include the entry for disconnected ECU(ECU that doesn't respond recent status queries).

### CODE REVIEW

**Comment by obi-t4** [comment]
@Bodong-Yang 
I can't approve since there are no changes.

image

**Comment by Bodong-Yang** [comment]
@obi-t4 Ah is the PR description OK? If so I will approve it, thanks!

**Comment by obi-t4** [comment]
@Bodong-Yang
Ah sorry, I submitted this PR :-)

**Comment by obi-t4** [comment]
Yes, the description is OK!

**Review by Bodong-Yang — APPROVED** [review]

**Pull request merged**
