### PR TITLE
Report download_bytes during OTA update

### PR DESCRIPTION
**Pull request by Bodong-Yang**
## Introduction
This PR update the `otaclient_proto`, add a new field `download_bytes` in `StatusProgress` message to indicate the actual data transfer volume during OTA update, and integrate the new compiled `otaclient_proto` into the otaclient.

## Changes
1. otaclient_proto: update `StatusProgress`, add `download_bytes` field
2. requirements.txt: bump to use grpcio and grpcio-tools to 1.50.0
3. update_stats: support for recording `download_bytes`
4. create_standby: integrate according to new update_stats module

## Ticket
[T4PB-22482](https://tier4.atlassian.net/browse/T4PB-22482)

### CODE REVIEW

**Comment by Bodong-Yang** [comment]
Dependency problem occurs as the newer grpcio/protobuf version is used. I will mark the PR as draft before I resolve this problem.

**Comment by obi-t4** [comment]
update docs/SERVICES.md by:
```
docker run --rm -v $(pwd)/docs:/out -v $(pwd)/proto:/protos pseudomuto/protoc-gen-doc --doc_opt=markdown,SERVICES.md
```
Above instruction is described in DEVELOPMENT.md.

**Comment by Bodong-Yang** [comment]
The problem of protobuf and grpcio & tools seems not being fixed yet, I will find a latest available version to use.

**Comment by Bodong-Yang** [comment]
@obi-t4 it works as expected!
```
[2022-10-20 16:14:12,964][DEBUG]-_status_call.py:call_status:35,response.data=ecu {
  ecu_id: "autoware"
  status {
    status: UPDATING
    version: "20221013091746-22.04-1st-sub"
    progress {
      phase: REGULAR
      total_regular_files: 294680
      regular_files_processed: 4393
      files_processed_copy: 1004
      files_processed_download: 3389
      file_size_processed_copy: 85985766
      file_size_processed_download: 113073540
      elapsed_time_copy {
        seconds: 1
        nanos: 98930279
      }
      elapsed_time_download {
        nanos: 924537405
      }
      total_regular_file_size: 23637537004
      total_elapsed_time {
        seconds: 19
        nanos: 440307382
      }
      download_bytes: 74194064
    }
  }
}
available_ecu_ids: "autoware"

```

**Review by obi-t4 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
