### PR TITLE
ota_client: optimize the way to convert path to url

### PR DESCRIPTION
**Pull request by Bodong-Yang**
This PR refers to the way of converting the unix path to URI from python's pathlib. 
The conversion and urljoin will all be done in the `Downloader` now.

### CODE REVIEW

**Comment by obi-t4** [comment]
@Bodong-Yang Did you test on the actual environment?

**Comment by Bodong-Yang** [comment]
> @Bodong-Yang Did you test on the actual environment?

Only pytest is tried. Can you help me confirm it on the actual environment?

**Comment by obi-t4** [comment]
> Only pytest is tried. Can you help me confirm it on the actual environment?

Before you submit the PR, actual environment (VirtualBox is OK) should be confirmed.

**Comment by Bodong-Yang** [comment]
> > Only pytest is tried. Can you help me confirm it on the actual environment?
> 
> Before you submit the PR, actual environment (VirtualBox is OK) should be confirmed.

I just finished the test on VM environment and the downloading functionality works as expected!
Please also confirm it on your side, if test is also passed, then the PR is OK I think.

**Comment by Bodong-Yang** [comment]
> > Only pytest is tried. Can you help me confirm it on the actual environment?
> 
> Before you submit the PR, actual environment (VirtualBox is OK) should be confirmed.

Working as expected confirmed on my side, please also confirm it on your side, then I think the PR is ready.

**Review by obi-t4 — APPROVED** [review]
Confirmed! :+1:

**Pull request merged**
