### PR TITLE
[Refine] downloader: improve chunk writing and decompression

### PR DESCRIPTION
**Pull request by Bodong-Yang**
## Introduction
This PR refines the implementation of downloader decompressing and saving data chunk.

## Test result
In my local setup, with compression enabled, the time cost of whole ota update reduce from *1088* down to *990*, considering my PC uses nvme and test is done with local prepared ota image, I think the performance in the real environment should also be improved in some extend.

## related issue report
https://tier4.atlassian.net/browse/T4PB-25078, which is handled in https://github.com/tier4/ota-client/pull/190.

### CODE REVIEW

**Comment by Bodong-Yang** [comment]
This PR only changes `downloader.py`, so It is possible to back-port this PR to v3.2.x.

**Comment by obi-t4** [comment]
@Bodong-Yang 
This PR improves 9% on your environment and that environment is low I/O usage. So why do you think

> the improvement will be significant in real environment.

On the real environment, IO usage is higher than your environment one, and on the high IO usage environment, decompression time can be hided by the IO usage.

**Comment by Bodong-Yang** [comment]
> @Bodong-Yang (This PR itself is OK) This PR improves 9% on your environment and that environment is low I/O usage. So why do you think
> 
> > the improvement will be significant in real environment.
> 
> On the real environment, IO usage is higher than your environment one, and on the high IO usage environment, decompression time can be hided by the IO usage.

My environment is I/O heavy because there is very little diff between my VM image and OTA image(the otaclient will have to download 7GB even with compression enabled, basically downloading the whole image).

But anyway that is only my guess, the test in real environment is still needed.

**Comment by Bodong-Yang** [comment]
( If it is possible, we can backport this PR to v3.2.0, and prepare a image for x1 team to test.

**Comment by Bodong-Yang** [comment]
@obi-t4 I remember that we have handled similar issue(https://tier4.atlassian.net/browse/T4PB-25078) for v3.2.2, and this issue also existed in v3.2.0(download thread num is too small(3), the fix(#190) is to enlarge download thread to 7), I think that is the main cause.

But anyway this PR also improves the performance, so it is better to apply it also.

**Comment by obi-t4** [comment]
> I remember that we have handled similar issue(https://tier4.atlassian.net/browse/T4PB-25078) for v3.2.2, and this issue also existed in v3.2.0(download thread num is too small(3), the fix(https://github.com/tier4/ota-client/pull/190) is to enlarge download thread to 7), I think that is the main cause.

Yes, this issue has been fixed by changing number of thread to 7 #190 

> But anyway this PR also improves the performance, so it is better to apply it also.

Yes, I think so, I'm waiting your:
> the test in real environment is still needed.

PR itself is OK since this can reduce usage of memory I think.

**Review by obi-t4 — APPROVED** [review]
LGTM :+1:

**Comment by Bodong-Yang** [comment]
The improvement is confirmed on v3.2.3!
Test setup: 
- **total_regular_files: 23637537004**
- **processed_files_download: 20703405289**

1. Without this PR, time cost is 1008 seconds
2. with this PR, time cost is 980 seconds, the memory usage is also slightly reduced(10MB less than 1)

I will merge this PR now.

**Pull request merged**
