### PR TITLE
[hotfix] proto_whl: include previous ver0.5.0 wheel

### PR DESCRIPTION
**Pull request by Bodong-Yang**
## Introduction
In PR#174, a new field for StatusProgress is introduced(download_bytes), and otaclient_pb2 is rebuilt under ver0.6.0. 
But I also accidentally rebuilt and override the 0.5.0 wheel. 
This PR reverts the change to 0.5.0 wheel by pick 0.5.0 wheel from commit before PR#174

### CODE REVIEW

**Comment by obi-t4** [comment]
```
((a825ea2...))$ sha256sum whl/otaclient_pb2-0.5.0.33632fb-py3-none-any.whl 
15713d4dbe115e925fb7b15acf6e992b22d10fae94b327f478eeaac857cbadfc  whl/otaclient_pb2-0.5.0.33632fb-py3-none-any.whl
```
```
(hotfix/proto_whl)$ sha256sum whl/otaclient_pb2-0.5.0.33632fb-py3-none-any.whl 
3ba458941c2a0878a606902594779e9380c2c6132864d9ea1b6cc5433b8ddd02  whl/otaclient_pb2-0.5.0.33632fb-py3-none-any.whl
```

**Comment by obi-t4** [comment]
@Bodong-Yang 
It seems different.

**Comment by Bodong-Yang** [comment]
> @Bodong-Yang It seems different.

Oh I will pick another one that match the hash value.

**Comment by Bodong-Yang** [comment]
@obi-t4 Correct 0.5.0 wheel is included, please have a check, thanks!

**Review by obi-t4 — DISMISSED** [review]
LGTM :+1:

**Review by obi-t4 — APPROVED** [review]

**Pull request merged**
